#!/usr/bin/env bash
# Copyright 2019 Vivid Inc.

# Referencing https://github.com/technomancy/leiningen/blob/master/sample.project.clj


clojure - <<EOS
(require 'clojure.java.shell)
(require 'vivid.art)
(let [in (:out (clojure.java.shell/sh "tail" "-c" "+356" "$0"))
      out (vivid.art/render in)]
  (spit "project.clj" out))
(System/exit 0)
EOS
exit


<%

(require 'clojure.pprint)

(def ^:const CLOJURE-VERSIONS
  ["1.9.0" "1.10.0" "1.10.1"])

(defn lein-profile-name-for-clojure-version
  [clojure-version]
  (format "clojure-%s" clojure-version))

(defn test-dependency-block
  [clojure-version]
  [(keyword (lein-profile-name-for-clojure-version clojure-version))
   {:dependencies [['org.clojure/clojure clojure-version]]}])

(def ^:const CLOJURE-VERSION-PROFILES
  (into {} (for [v CLOJURE-VERSIONS]
             (test-dependency-block v))))

(def ^:const CLOJURE-TEST-PROFILES-STR
  (clojure.string/join ":"
                       (map #(str "+" (lein-profile-name-for-clojure-version %)) CLOJURE-VERSIONS)))

(def ^:const PROFILES
  (merge
    '{:dev {:dependencies   [;; Diffs equality assertions in test failure output
                             ;; https://github.com/pjstadig/humane-test-output
                             [pjstadig/humane-test-output "0.10.0"]]

            :injections     [(require 'pjstadig.humane-test-output)
                             (pjstadig.humane-test-output/activate!)

                             ; Keep Spec enabled in the context of development of ART,
                             ; but not in the shipping jar.
                             ;
                             ; Load all namespaces in the project + Spec
                             (require 'vivid.art)
                             (require 'clojure.spec.test.alpha)
                             ; Instrument everything Spec can find
                             (clojure.spec.test.alpha/instrument)]

            :plugins        [;; Reloads & re-runs tests on file changes
                             ;; https://github.com/jakemcc/lein-test-refresh
                             [com.jakemccrary/lein-test-refresh "0.24.1"]]

            :resource-paths ["test-resources"]

            :test-refresh   {:quiet true}}}
    CLOJURE-VERSION-PROFILES))

%>(defproject
  vivid/art "0.5.0"

  :note "THIS FILE IS AUTOMATICALLY GENERATED BY gen-project.clj"
  :description "Ash Ra Template: Expressive template system for Clojure."
  :url "https://github.com/vivid-inc/ash-ra-template"
  :license {:distribution :repo
            :name         "Apache License 2.0"
            :url          "https://www.apache.org/licenses/LICENSE-2.0"}

  :dependencies [[instaparse "1.4.10" :exclusions [org.clojure/spec.alpha]]
                 [special "0.1.3-Beta1"]
                 [org.clojure/tools.deps.alpha "0.7.516" :exclusions [commons-logging
                                                                      org.slf4j/slf4j-api]]
                 [org.projectodd.shimdandy/shimdandy-api "1.2.1"]
                 [org.projectodd.shimdandy/shimdandy-impl "1.2.1"]
                 [org.xeustechnologies/jcl-core "2.8"]
                 [reduce-fsm "0.1.4"]]

  :aliases {"build"    ["do"
                        "version,"
                        "clean,"
                        "cloverage,"
                        "eastwood,"
                        "jar,"
                        "install"]
            "test-all" ["with-profile" "<%= CLOJURE-TEST-PROFILES-STR %>" "build"]}

  :cloverage {:codecov? true
              :html?    false
              :output   "."                                 ; "lein jar" appears to destroy target/coverage/codecov.json
              }

  ;test/vivid/art/api_contract_test.clj:70:5: unused-ret-vals-in-try: Return value is discarded for a function call that only has side effects if the functions passed to it as args have side effects inside body of try: (apply art/failure? [])
  :eastwood {:exclude-linters []
             :namespaces      [:source-paths]}

  :exclusions [org.clojure/clojure]

  :global-vars {*warn-on-reflection* true}

  :javac-options ["-target" "1.8"]

  :manifest {"Built-By" "vivid"}

  :min-lein-version "2.9.1"

  ; Note: Enable only to more strictly inspect dependencies
  ;:pedantic? :abort

  :plugins [[jonase/eastwood "0.3.5"]
            [lein-ancient "0.6.15"]
            [lein-cloverage "1.1.1"]
            [lein-kibit "0.1.6"]
            [lein-nvd "1.1.0" :exclusions [org.slf4j/jcl-over-slf4j
                                           org.slf4j/slf4j-api]]
            [venantius/yagni "0.1.7"]]

  :profiles <%= (with-out-str (clojure.pprint/pprint PROFILES)) %>

  :repositories [["clojars" {:sign-releases false}]])
